# theme = "catppuccin_mocha"
# theme = "tokyonight"
# theme = "dracula"
# theme = "base16_transparent"
theme = "kanagawa"
# theme = "ayu_dark"

[editor]
line-number = "relative"
mouse = false
auto-completion = true
auto-format = true
cursorline = true
# cursorcolumn = true
color-modes = true
true-color = true
completion-timeout = 15
rulers = [80]
bufferline = "multiple"
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"
default-yank-register = "+"
end-of-line-diagnostics = "hint"
# shell = ["nu"]

[editor.inline-diagnostics]
# cursor-line = "error"
cursor-line = "warning"
other-lines = "error"
max-diagnostics = 2

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-wrap = 10 # increase to reduce forced mid-word wrapping
# max-indent-retain = 14
# wrap-at-text-width = true
wrap-indicator = ""
[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = [
	"diagnostics",
	"workspace-diagnostics",
	"selections",
	"file-type",
	"file-encoding",
	"position-percentage",
	"position",
]

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.lsp]
auto-signature-help = true
display-messages = true
display-inlay-hints = true

[editor.smart-tab]
enable = true
supersede-menu = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
D = ["ensure_selections_forward", "extend_to_line_end"]
x = ["extend_line"]
ins = "insert_mode"
esc = ["collapse_selection", "keep_primary_selection"]
# C-o = ":open ~/.config/helix/config.toml" # Maps Ctrl-o to opening of the helix config file
C-r = ":config-reload"
C-g = [ # LazyGit
	":write-all",
	":new",
	":insert-output lazygit",
	":buffer-close!",
	":redraw",
	":reload-all",
]
"A-x" = "@x<A-d>" # maps Alt-x to a macro selecting the whole line and deleting it without yanking it
H = ":buffer-previous"
L = ":buffer-next"
C-q = ":buffer-close"

g = {a = "code_action"}        # ga to open code actions
X = "extend_line_above"        # Shift+x to select the whole line above
"tab" = "goto_next_function"   # Select and jump to the next function via Treesitter
"S-tab" = "goto_prev_function" # Select and jump to the previous function via Treesitter 
# Use system clipboard
# P = "paste_clipboard_before"
# p = "replace_selections_with_clipboard"
# y = "yank_main_selection_to_clipboard"
"*" = [
	"move_prev_word_start",
	"move_next_word_end",
	"search_selection",
	"global_search",
]
# Mark line and move with them up/down
# https://github.com/helix-editor/helix/discussions/5764#discussioncomment-4840408
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
	"extend_to_line_bounds",
	"delete_selection",
	"move_line_up",
	"paste_before",
]

[keys.normal.space]
e = [ # Yazi
	":sh rm -f /tmp/unique-file-h21a434",
	":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-h21a434",
	":insert-output echo \"x1b[?1049h\" > /dev/tty",
	":open %sh{cat /tmp/unique-file-h21a434}",
	":redraw",
]
"." = ":fmt"
x = ":toggle whitespace.render all none"
q = ":quit"
# [keys.select.ret]
# s = ":sh tmux popup -xC -yC -w90% -h90% -E scooter"
[keys.normal.space.t]
# Zen-Mode
z = ":toggle gutters.line-numbers.min-width 52 3"
[keys.select]
";" = ["collapse_selection", "normal_mode"]
x = "extend_line"
V = "extend_to_line_end"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
# Make selecting lines in visual mode behave sensibly
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
G = "goto_file_end"
S = "surround_add"

[keys.normal.z]
j = "scroll_up"
k = "scroll_down"
[keys.normal."+"]
b = ":run-shell-command cargo build"
r = ":run-shell-command cargo run"
t = ":run-shell-command cargo test"

[keys.insert]
j = {k = "normal_mode"}

C-space = "completion"
# Move cursor in insert mode
A-j = "move_line_down"
A-h = "move_char_left"
A-k = "move_line_up"
A-l = "move_char_right"
A-o = "open_below"
A-O = "open_above"

[editor.file-picker]
hidden = false


# [extensions]
# my_status_line = {
# enabled = true,
# command = ["/home/jr/.helix/helix_status.sh"]
# }
